"""empty message

Revision ID: 12b6cdc4b018
Revises: 8cdbe9c8bb25
Create Date: 2025-12-14 02:08:09.952834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b6cdc4b018'
down_revision: Union[str, Sequence[str], None] = '8cdbe9c8bb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('video_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('likes_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('reports_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('comments_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('creator_id', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rlt_bot'
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('views_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('likes_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('reports_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('comments_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('delta_views_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('delta_likes_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('delta_reports_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('delta_comments_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['rlt_bot.videos.id'], name='video_snapshots_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rlt_bot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots', schema='rlt_bot')
    op.drop_table('videos', schema='rlt_bot')
    # ### end Alembic commands ###
